---
name: push branches
on:
  push:
    branches:
     - main
     - dev
     - qa 
  pull_request:
    branches:
     - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: this is branch job 
       run: echo " this is new branch job "