name: env1
on: workflow_dispatch
env:
  APP_NAME: "Sai"
jobs:
  envjob:
    runs-on: ubuntu-latest
    env:
      APP_NAME: "Sai12"
    steps:
     - name: checking prority
       env:
       APP_NAME: "Sai1234"
          run: echo " Welcome to $APP_NAME "
