name: input 2 field param
on: 
  workflow_dispatch: 
    inputs:
      environment: 
        description: choose the environment to deploy 
        required: true 
        default: dev 
      default_args:
        description: Choose the envieonment to deploy default
        required: true
        default: 0.0.1
jobs:
  inputparam:
    runs-on: ubuntu-latest
    steps:
      - name: print the variable 
        run: echo " this is the job executed on ${{inputs.environment}}"
